In [1]:
import pandas as pd
import quandl

In [2]:
df= quandl.get('WIKI/GOOGL')

In [4]:
df.shape

(2948, 12)

In [5]:
df.head()

Open    High     Low   Close      Volume  Ex-Dividend  \
Date                                                                  
2004-08-19  100.00  104.06   95.96  100.34  44659000.0          0.0   
2004-08-20  101.01  109.08  100.50  108.31  22834300.0          0.0   
2004-08-23  110.75  113.48  109.05  109.40  18256100.0          0.0   
2004-08-24  111.24  111.60  103.57  104.87  15247300.0          0.0   
2004-08-25  104.96  108.00  103.88  106.00   9188600.0          0.0   

            Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  \
Date                                                                  
2004-08-19          1.0     50.000      52.03    47.980      50.170   
2004-08-20          1.0     50.505      54.54    50.250      54.155   
2004-08-23          1.0     55.375      56.74    54.525      54.700   
2004-08-24          1.0     55.620      55.80    51.785      52.435   
2004-08-25          1.0     52.480      54.00    51.940      53.000   

            Adj. Volume  
Date                     
2004-08-19   44659000.0  
2004-08-20   22834300.0  
2004-08-23   18256100.0  
2004-08-24   15247300.0  
2004-08-25    9188600.0

In [7]:
df.describe()

Open         High          Low        Close        Volume  \
count  2948.000000  2948.000000  2948.000000  2948.000000  2.948000e+03   
mean    547.906873   553.215045   542.027564   547.643739  8.798494e+06   
std     199.579325   200.268851   198.527571   199.429059  8.484761e+06   
min      99.190000   101.740000    95.960000   100.010000  5.211410e+05   
25%     431.717500   439.170000   425.552500   432.460000  3.628100e+06   
50%     542.950000   547.025000   537.145000   542.230000  6.028200e+06   
75%     628.002500   634.020000   621.297500   626.062500  1.155565e+07   
max    1226.800000  1228.880000  1218.600000  1220.170000  8.215110e+07   

       Ex-Dividend  Split Ratio    Adj. Open    Adj. High     Adj. Low  \
count       2948.0       2948.0  2948.000000  2948.000000  2948.000000   
mean           0.0          1.0   329.594090   332.726471   326.089288   
std            0.0          0.0   171.595528   172.693219   170.158647   
min            0.0          1.0    49.595000    50.870000    47.980000   
25%            0.0          1.0   215.858750   219.585000   212.776250   
50%            0.0          1.0   280.662500   283.915000   277.092500   
75%            0.0          1.0   433.428750   436.797500   430.485000   
max            0.0          1.0   800.500000   810.350000   787.200000   

        Adj. Close   Adj. Volume  
count  2948.000000  2.948000e+03  
mean    329.431755  8.798494e+06  
std     171.471923  8.484761e+06  
min      50.005000  5.211410e+05  
25%     216.230000  3.628100e+06  
50%     280.400000  6.028200e+06  
75%     433.350000  1.155565e+07  
max     793.960000  8.215110e+07

In [11]:
df.index.min(), df.index.max()

(Timestamp('2004-08-19 00:00:00'), Timestamp('2016-05-20 00:00:00'))

In [12]:
import numpy as np

In [21]:
print np.corrcoef([df.High, df.Low, df.Open, df.Close])

[[ 1.          0.99950893  0.99970672  0.99962496]
 [ 0.99950893  1.          0.99955576  0.99968911]
 [ 0.99970672  0.99955576  1.          0.99925693]
 [ 0.99962496  0.99968911  0.99925693  1.        ]]


In [22]:
df= df[['Adj. Open', 'Adj. Close', 'Adj. High', 'Adj. Low', 'Adj. Volume']]

In [23]:
df.head()

Adj. Open  Adj. Close  Adj. High  Adj. Low  Adj. Volume
Date                                                               
2004-08-19     50.000      50.170      52.03    47.980   44659000.0
2004-08-20     50.505      54.155      54.54    50.250   22834300.0
2004-08-23     55.375      54.700      56.74    54.525   18256100.0
2004-08-24     55.620      52.435      55.80    51.785   15247300.0
2004-08-25     52.480      53.000      54.00    51.940    9188600.0

In [25]:
df['hl_pct'] = (df['Adj. High'] - df['Adj. Low'])/df['Adj. Low'] * 100.0

/home/arko/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [26]:
df['pct_change'] = (df['Adj. Close'] - df['Adj. Open'])/df['Adj. Open'] * 100.0

/home/arko/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [27]:
df.head()

Adj. Open  Adj. Close  Adj. High  Adj. Low  Adj. Volume    hl_pct  \
Date                                                                            
2004-08-19     50.000      50.170      52.03    47.980   44659000.0  8.441017   
2004-08-20     50.505      54.155      54.54    50.250   22834300.0  8.537313   
2004-08-23     55.375      54.700      56.74    54.525   18256100.0  4.062357   
2004-08-24     55.620      52.435      55.80    51.785   15247300.0  7.753210   
2004-08-25     52.480      53.000      54.00    51.940    9188600.0  3.966115   

            pct_change  
Date                    
2004-08-19    0.340000  
2004-08-20    7.227007  
2004-08-23   -1.218962  
2004-08-24   -5.726357  
2004-08-25    0.990854

In [28]:
df= df[['Adj. Close', 'hl_pct', 'pct_change', 'Adj. Volume']]

In [29]:
df.head()

Adj. Close    hl_pct  pct_change  Adj. Volume
Date                                                     
2004-08-19      50.170  8.441017    0.340000   44659000.0
2004-08-20      54.155  8.537313    7.227007   22834300.0
2004-08-23      54.700  4.062357   -1.218962   18256100.0
2004-08-24      52.435  7.753210   -5.726357   15247300.0
2004-08-25      53.000  3.966115    0.990854    9188600.0

In [30]:
df.fillna(-99999, inplace= True)

In [39]:
import math
forecast_col= 'Adj. Close'
forecast_out= int(math.ceil(0.01*len(df)))
forecast_out

30

In [40]:
df['label']= df[forecast_col].shift(-forecast_out)
df.head()

Adj. Close    hl_pct  pct_change  Adj. Volume   label
Date                                                             
2004-08-19      50.170  8.441017    0.340000   44659000.0  66.290
2004-08-20      54.155  8.537313    7.227007   22834300.0  67.530
2004-08-23      54.700  4.062357   -1.218962   18256100.0  69.185
2004-08-24      52.435  7.753210   -5.726357   15247300.0  68.540
2004-08-25      53.000  3.966115    0.990854    9188600.0  69.425

In [41]:
df.tail()

Adj. Close    hl_pct  pct_change  Adj. Volume  label
Date                                                            
2016-05-16      730.30  1.761111    0.825602    1106682.0    NaN
2016-05-17      720.19  2.486072   -1.486882    1631175.0    NaN
2016-05-18      721.78  1.475483    0.456507    1607604.0    NaN
2016-05-19      715.31  1.435299   -0.416261    1488030.0    NaN
2016-05-20      721.71  1.774800    0.732769    1710030.0    NaN

In [42]:
df.shape

(2948, 5)

In [43]:
df.dropna(inplace=True)

In [44]:
df.shape

(2918, 5)

In [45]:
from sklearn import preprocessing